{
 "title": "Kubensage Nodes Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Node",
    "query": {
     "query": "label_values(node_cpu_usage_percent,hostname)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Node informations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "description": "Node hostname",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_cpu_usage_percent{hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 21, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "node_cpu_usage_percent{hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory/CPU/Processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Node memory",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 16, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_total_bytes{hostname=\"$hostname\"}",
     "legendFormat": "Total memory on node '{{hostname}}'"
    },
    {
     "expr": "node_memory_available_bytes{hostname=\"$hostname\"}",
     "legendFormat": "Available memory on node '{{hostname}}'"
    },
    {
     "expr": "node_memory_used_bytes{hostname=\"$hostname\"}",
     "legendFormat": "Used memory on node '{{hostname}}'"
    }
   ]
  },
  {
   "title": "Node uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_uptime_seconds{hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node memory used percentage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_used_perc{hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node total processes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_total_procs{hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node CPU usage percentage",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "node_cpu_usage_percent{hostname=\"$hostname\"}",
     "legendFormat": "OS: {{os}} / Platform: {{platform}} / Kernel arch: {{kernel_arch}}"
    }
   ]
  },
  {
   "title": "Top 'n' memory hungry node processes (LIVE)",
   "type": "barchart",
   "description": "'n' is the number of processes watched by the agent (default: 10 processes)",
   "gridPos": { "h": 14, "w": 14, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sort_desc(processes_mem_info{hostname=\"$hostname\"})",
     "legendFormat": "{{name}} (pid: {{pid}})"
    }
   ]
  },
  {
   "title": "Node single core usage percentage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_single_cpu_usage{hostname=\"$hostname\"}",
     "legendFormat": "Core #{{cpu_id}}"
    }
   ]
  },
  {
   "title": "Node CPU clock speed in GHz",
   "type": "stat",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_clock_cpu_speed{hostname=\"$hostname\"}",
     "legendFormat": "Core #{{cpu_id}}"
    }
   ]
  },
  {
   "title": "Node PSI memory",
   "type": "timeseries",
   "description": "Cumulative time (in microseconds) that tasks have been stalled due to memory pressure since system boot",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "node_mem_psi_stall_millis_total{hostname=\"$hostname\"}",
     "legendFormat": "Memory PSI"
    }
   ]
  },
  {
   "title": "Node PSI CPU",
   "type": "timeseries",
   "description": "Cumulative time (in microseconds) that tasks have been stalled due to cpu pressure since system boot",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "node_cpu_psi_stall_millis_total{hostname=\"$hostname\"}",
     "legendFormat": "CPU PSI"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Node network incoming traffic",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_net_byte_received_total{hostname=\"$hostname\"}[1m])",
     "legendFormat": "Download speed (bytes/s)"
    }
   ]
  },
  {
   "title": "Node network outgoing traffic",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_net_byte_sent_total{hostname=\"$hostname\"}[1m])",
     "legendFormat": "Upload speed (bytes/s)"
    }
   ]
  },
  {
   "title": "Total node byte sent/received over the network",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_net_byte_sent_total{hostname=\"$hostname\"}",
     "legendFormat": "SENT"
    },
    {
     "expr": "node_net_byte_received_total{hostname=\"$hostname\"}",
     "legendFormat": "RECEIVED"
    }
   ]
  },
  {
   "title": "Total node packet error",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_net_total_inbound_packet_error{hostname=\"$hostname\"}",
     "legendFormat": "INBOUND"
    },
    {
     "expr": "node_net_total_outbound_packet_error{hostname=\"$hostname\"}",
     "legendFormat": "OUTBOUND"
    }
   ]
  },
  {
   "title": "Total node FIFO buffer error",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_net_total_inbound_fifo_buffer_error{hostname=\"$hostname\"}",
     "legendFormat": "INBOUND"
    },
    {
     "expr": "node_net_total_outbound_fifo_buffer_error{hostname=\"$hostname\"}",
     "legendFormat": "OUTBOUND"
    }
   ]
  },
  {
   "title": "Total node packets sent/received over the network",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_net_total_packet_sent{hostname=\"$hostname\"}",
     "legendFormat": "SENT"
    },
    {
     "expr": "node_net_total_packet_received{hostname=\"$hostname\"}",
     "legendFormat": "RECEIVED"
    }
   ]
  },
  {
   "title": "Total node packet dropped",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_net_total_inbound_packet_dropped{hostname=\"$hostname\"}",
     "legendFormat": "INBOUND"
    },
    {
     "expr": "node_net_total_outbound_packet_dropped{hostname=\"$hostname\"}",
     "legendFormat": "OUTBOUND"
    }
   ]
  },
  {
   "title": "Node network interfaces",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "node_net_interfaces{hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "Node disk read speed in bytes/s",
   "type": "timeseries",
   "description": "Node disk read speed. This is cumulative, across all disks discovered by the agent",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{hostname=\"$hostname\"}[1m])",
     "legendFormat": "READ speed bytes/s"
    }
   ]
  },
  {
   "title": "Node disk write speed in bytes/s",
   "type": "timeseries",
   "description": "Node disk write speed. This is cumulative, across all disks discovered by the agent",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_disk_write_bytes_total{hostname=\"$hostname\"}[1m])",
     "legendFormat": "WRITE speed bytes/s"
    }
   ]
  },
  {
   "title": "Node disk space",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_disk_free_bytes{hostname=\"$hostname\"}",
     "legendFormat": "Free space on: {{device}}"
    },
    {
     "expr": "node_disk_used_bytes{hostname=\"$hostname\"}",
     "legendFormat": "Used space on: {{device}}"
    },
    {
     "expr": "node_disk_capacity_total_bytes{hostname=\"$hostname\"}",
     "legendFormat": "Total capacity on: {{device}}"
    }
   ]
  },
  {
   "title": "Node disk total bytes read ops",
   "type": "stat",
   "description": "Total read operations across all disks. This is cumulative",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_disk_read_ops_total{hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node disk total bytes write ops",
   "type": "stat",
   "description": "Total write operations across all disks. This is cumulative.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_disk_write_ops_total{hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node disk total bytes read",
   "type": "stat",
   "description": "Total bytes read from all disks. This is cumulative, across all disks discovered",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_disk_read_bytes_total{hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node disk usage percentage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_disk_used_perc{hostname=\"$hostname\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Node disk total bytes write",
   "type": "stat",
   "description": "Total bytes write from all disks. This is cumulative, across all disks discovered",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_disk_write_bytes_total{hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node PSI Disk I/O",
   "type": "timeseries",
   "description": "Cumulative time (in microseconds) that tasks have been stalled due to disk pressure since system boot",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "node_io_psi_stall_millis_total{hostname=\"$hostname\"}",
     "legendFormat": "Disk I/O PSI"
    }
   ]
  }
 ]
}