{
 "title": "Kubensage Pods and Containers Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Node",
    "query": {
     "query": "label_values(node_cpu_usage_percent,hostname)"
    }
   },
   {
    "name": "podList",
    "label": "Pod",
    "query": {
     "query": "label_values(node_pods_list{hostname=\"$hostname\"},pod)"
    }
   },
   {
    "name": "containerStatus",
    "label": "Container status",
    "query": "CONTAINER_RUNNING, CONTAINER_EXITED"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "PODS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pod list",
   "type": "table",
   "description": "Pod list with infos",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "node_pods_list{hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers per Pod",
   "type": "table",
   "description": "Each container running in one pod. Containers are comma separated.",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "node_container_list{hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CONTAINERS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Container memory usage",
   "type": "timeseries",
   "description": "Container memory usage. This panel is filtered by top page variable",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{hostname=\"$hostname\", pod=\"$podList\", state=\"$containerStatus\"}",
     "legendFormat": "Pod: {{pod}} -> Container: {{container}}"
    }
   ]
  },
  {
   "title": "Container CPU usage",
   "type": "timeseries",
   "description": "Container CPU usage percentage. This panel is filtered by top page variable",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(container_cpu_usage_nano_cores{hostname=\"$hostname\", pod=\"$podList\", state=\"$containerStatus\"} / 1e9) * 100",
     "legendFormat": "Pod: {{pod}} -> Container: {{container}}"
    }
   ]
  }
 ]
}